# Generated by Django 4.2.5 on 2023-12-15 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toursPage', '0010_category_tour_cat'),
        ('reportsPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='tour',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='toursPage.tour'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
