# Generated by Django 4.2.5 on 2023-12-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsPage', '0002_feedback_tour_alter_feedback_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='text',
            field=models.TextField(default='text_of_feedback', max_length=30000, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='username',
            field=models.CharField(default='username', max_length=255, verbose_name='Имя пользователя'),
        ),
    ]
