# Generated by Django 4.2.5 on 2023-12-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsPage', '0010_alter_feedback_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='username',
            field=models.CharField(default='Имя', max_length=255, verbose_name='Имя пользователя'),
        ),
    ]
