# Generated by Django 4.2.5 on 2023-09-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_remove_user_request_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='e_mail',
            field=models.EmailField(max_length=255, verbose_name='e-mail address'),
        ),
    ]
