# Generated by Django 4.2.5 on 2023-09-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0003_alter_user_e_mail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Employer',
        ),
    ]
