# Generated by Django 4.2.5 on 2023-10-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='isIdividual',
            new_name='isIndividual',
        ),
    ]
