# Generated by Django 4.2.5 on 2023-10-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationPage', '0002_rename_isidividual_customer_isindividual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='isIndividual',
            field=models.BooleanField(default=False),
        ),
    ]
