# Generated by Django 4.2.5 on 2023-11-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationPage', '0003_alter_customer_isindividual'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
