# Generated by Django 4.2.5 on 2023-10-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Длительность тура'),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_available_for_children',
            field=models.BooleanField(default=True, verbose_name='Подходит для детей'),
        ),
        migrations.AddField(
            model_name='tour',
            name='number_of_tourists',
            field=models.IntegerField(default=0, verbose_name='Количество человек в группе'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_name',
            field=models.CharField(default='Название тура', max_length=255, verbose_name='Tour name'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Стоимость'),
        ),
    ]
