# Generated by Django 4.2.5 on 2023-10-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursPage', '0005_alter_visual_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(default='Название тура', max_length=255, verbose_name='Tour name')),
                ('duration', models.IntegerField(default=0, verbose_name='Длительность тура')),
                ('number_of_tourists', models.IntegerField(default=0, verbose_name='Количество человек в группе')),
                ('is_available_for_children', models.BooleanField(default=True, verbose_name='Подходит для детей')),
                ('price', models.IntegerField(default=0, verbose_name='Стоимость')),
                ('description', models.TextField(default='Описание тура')),
            ],
        ),
    ]
