# Generated by Django 4.2.5 on 2023-10-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toursPage', '0006_tourdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TourDetails',
            new_name='TourDetail',
        ),
    ]
