# Generated by Django 4.2.5 on 2023-10-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursPage', '0007_rename_tourdetails_tourdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdetail',
            name='tour_id',
            field=models.IntegerField(default=0, verbose_name='ID тура'),
        ),
    ]
